// This file was initially generated by Windows Terminal 1.3.2651.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "fontFace": "MesloLGM NF", //"JetBrains Mono",
            "fontSize": 10
        },
        "list":
        [
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false,
                "colorScheme": "Atom"
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false,
                "colorScheme": "Solarized Dark Higher Contrast"
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore",
                "colorScheme": "Andromeda"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "colorScheme": "Andromeda"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{a3a2e83a-884a-5379-baa8-16f193a13b21}",
                "hidden": false,
                "name": "PowerShell 7 Preview",
                "source": "Windows.Terminal.PowershellCore"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    // Get themes here: https://windowsterminalthemes.dev/
    "schemes": [
        {
            "name": "Atom",
            "black": "#000000",
            "red": "#fd5ff1",
            "green": "#87c38a",
            "yellow": "#ffd7b1",
            "blue": "#85befd",
            "purple": "#b9b6fc",
            "cyan": "#85befd",
            "white": "#e0e0e0",
            "brightBlack": "#000000",
            "brightRed": "#fd5ff1",
            "brightGreen": "#94fa36",
            "brightYellow": "#f5ffa8",
            "brightBlue": "#96cbfe",
            "brightPurple": "#b9b6fc",
            "brightCyan": "#85befd",
            "brightWhite": "#e0e0e0",
            "background": "#161719",
            "foreground": "#c5c8c6"
          },
          {
            "name": "Andromeda",
            "black": "#000000",
            "red": "#cd3131",
            "green": "#05bc79",
            "yellow": "#e5e512",
            "blue": "#2472c8",
            "purple": "#bc3fbc",
            "cyan": "#0fa8cd",
            "white": "#e5e5e5",
            "brightBlack": "#666666",
            "brightRed": "#cd3131",
            "brightGreen": "#05bc79",
            "brightYellow": "#e5e512",
            "brightBlue": "#2472c8",
            "brightPurple": "#bc3fbc",
            "brightCyan": "#0fa8cd",
            "brightWhite": "#e5e5e5",
            "background": "#262a33",
            "foreground": "#e5e5e5"
          },
          {
            "name": "Afterglow",
            "black": "#151515",
            "red": "#ac4142",
            "green": "#7e8e50",
            "yellow": "#e5b567",
            "blue": "#6c99bb",
            "purple": "#9f4e85",
            "cyan": "#7dd6cf",
            "white": "#d0d0d0",
            "brightBlack": "#505050",
            "brightRed": "#ac4142",
            "brightGreen": "#7e8e50",
            "brightYellow": "#e5b567",
            "brightBlue": "#6c99bb",
            "brightPurple": "#9f4e85",
            "brightCyan": "#7dd6cf",
            "brightWhite": "#f5f5f5",
            "background": "#212121",
            "foreground": "#d0d0d0"
          },
          {
            "name": "AdventureTime",
            "black": "#050404",
            "red": "#bd0013",
            "green": "#4ab118",
            "yellow": "#e7741e",
            "blue": "#0f4ac6",
            "purple": "#665993",
            "cyan": "#70a598",
            "white": "#f8dcc0",
            "brightBlack": "#4e7cbf",
            "brightRed": "#fc5f5a",
            "brightGreen": "#9eff6e",
            "brightYellow": "#efc11a",
            "brightBlue": "#1997c6",
            "brightPurple": "#9b5953",
            "brightCyan": "#c8faf4",
            "brightWhite": "#f6f5fb",
            "background": "#1f1d45",
            "foreground": "#f8dcc0"
          },
          {
            "name": "WarmNeon",
            "black": "#000000",
            "red": "#e24346",
            "green": "#39b13a",
            "yellow": "#dae145",
            "blue": "#4261c5",
            "purple": "#f920fb",
            "cyan": "#2abbd4",
            "white": "#d0b8a3",
            "brightBlack": "#fefcfc",
            "brightRed": "#e97071",
            "brightGreen": "#9cc090",
            "brightYellow": "#ddda7a",
            "brightBlue": "#7b91d6",
            "brightPurple": "#f674ba",
            "brightCyan": "#5ed1e5",
            "brightWhite": "#d8c8bb",
            "background": "#404040",
            "foreground": "#afdab6"
          },
          {
            "name": "Builtin Solarized Dark",
            "black": "#073642",
            "red": "#dc322f",
            "green": "#859900",
            "yellow": "#b58900",
            "blue": "#268bd2",
            "purple": "#d33682",
            "cyan": "#2aa198",
            "white": "#eee8d5",
            "brightBlack": "#002b36",
            "brightRed": "#cb4b16",
            "brightGreen": "#586e75",
            "brightYellow": "#657b83",
            "brightBlue": "#839496",
            "brightPurple": "#6c71c4",
            "brightCyan": "#93a1a1",
            "brightWhite": "#fdf6e3",
            "background": "#002b36",
            "foregr,ound": "#839496"
          },
          {
            "name": "Chalk",
            "black": "#7d8b8f",
            "red": "#b23a52",
            "green": "#789b6a",
            "yellow": "#b9ac4a",
            "blue": "#2a7fac",
            "purple": "#bd4f5a",
            "cyan": "#44a799",
            "white": "#d2d8d9",
            "brightBlack": "#888888",
            "brightRed": "#f24840",
            "brightGreen": "#80c470",
            "brightYellow": "#ffeb62",
            "brightBlue": "#4196ff",
            "brightPurple": "#fc5275",
            "brightCyan": "#53cdbd",
            "brightWhite": "#d2d8d9",
            "background": "#2b2d2e",
            "foreground": "#d2d8d9"
          },
          {
            "name": "Chester",
            "black": "#080200",
            "red": "#fa5e5b",
            "green": "#16c98d",
            "yellow": "#ffc83f",
            "blue": "#288ad6",
            "purple": "#d34590",
            "cyan": "#28ddde",
            "white": "#e7e7e7",
            "brightBlack": "#6f6b68",
            "brightRed": "#fa5e5b",
            "brightGreen": "#16c98d",
            "brightYellow": "#feef6d",
            "brightBlue": "#278ad6",
            "brightPurple": "#d34590",
            "brightCyan": "#27dede",
            "brightWhite": "#ffffff",
            "background": "#2c3643",
            "foreground": "#ffffff"
          },
          {
            "name": "Cobalt2",
            "black": "#000000",
            "red": "#ff0000",
            "green": "#38de21",
            "yellow": "#ffe50a",
            "blue": "#1460d2",
            "purple": "#ff005d",
            "cyan": "#00bbbb",
            "white": "#bbbbbb",
            "brightBlack": "#555555",
            "brightRed": "#f40e17",
            "brightGreen": "#3bd01d",
            "brightYellow": "#edc809",
            "brightBlue": "#5555ff",
            "brightPurple": "#ff55ff",
            "brightCyan": "#6ae3fa",
            "brightWhite": "#ffffff",
            "background": "#132738",
            "foreground": "#ffffff"
          },
          {
            "name": "Solarized Darcula",
            "black": "#25292a",
            "red": "#f24840",
            "green": "#629655",
            "yellow": "#b68800",
            "blue": "#2075c7",
            "purple": "#797fd4",
            "cyan": "#15968d",
            "white": "#d2d8d9",
            "brightBlack": "#25292a",
            "brightRed": "#f24840",
            "brightGreen": "#629655",
            "brightYellow": "#b68800",
            "brightBlue": "#2075c7",
            "brightPurple": "#797fd4",
            "brightCyan": "#15968d",
            "brightWhite": "#d2d8d9",
            "background": "#3d3f41",
            "foreground": "#d2d8d9"
          },
          {
            "name": "Solarized Dark - Patched",
            "black": "#002831",
            "red": "#d11c24",
            "green": "#738a05",
            "yellow": "#a57706",
            "blue": "#2176c7",
            "purple": "#c61c6f",
            "cyan": "#259286",
            "white": "#eae3cb",
            "brightBlack": "#475b62",
            "brightRed": "#bd3613",
            "brightGreen": "#475b62",
            "brightYellow": "#536870",
            "brightBlue": "#708284",
            "brightPurple": "#5956ba",
            "brightCyan": "#819090",
            "brightWhite": "#fcf4dc",
            "background": "#001e27",
            "foreground": "#708284"
          },
          {
            "name": "Solarized Dark Higher Contrast",
            "black": "#002831",
            "red": "#d11c24",
            "green": "#6cbe6c",
            "yellow": "#a57706",
            "blue": "#2176c7",
            "purple": "#c61c6f",
            "cyan": "#259286",
            "white": "#eae3cb",
            "brightBlack": "#006488",
            "brightRed": "#f5163b",
            "brightGreen": "#51ef84",
            "brightYellow": "#b27e28",
            "brightBlue": "#178ec8",
            "brightPurple": "#e24d8e",
            "brightCyan": "#00b39e",
            "brightWhite": "#fcf4dc",
            "background": "#001e27",
            "foreground": "#9cc2c3"
          }


    ],

    // Add custom actions and keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about actions and keybindings, visit https://aka.ms/terminal-keybindings
    "actions":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+Shift+F to open the search box
        { "command": "find", "keys": "ctrl+shift+f" },

        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        // or here https://docs.microsoft.com/en-us/windows/terminal/panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" },
        //create split screens
        { "command": { "action": "splitPane", "split": "vertical" }, "keys": "alt+shift+=" },
        { "command": { "action": "splitPane", "split": "horizontal" }, "keys": "alt+shift+-" },

        //navigate panes
        { "command": { "action": "moveFocus", "direction": "down" }, "keys": "alt+down" },
        { "command": { "action": "moveFocus", "direction": "left" }, "keys": "alt+left" },
        { "command": { "action": "moveFocus", "direction": "right" }, "keys": "alt+right" },
        { "command": { "action": "moveFocus", "direction": "up" }, "keys": "alt+up" },

        //resizing
        { "command": { "action": "resizePane", "direction": "down" }, "keys": "alt+shift+down" },
        { "command": { "action": "resizePane", "direction": "left" }, "keys": "alt+shift+left" },
        { "command": { "action": "resizePane", "direction": "right" }, "keys": "alt+shift+right" },
        { "command": { "action": "resizePane", "direction": "up" }, "keys": "alt+shift+up" },

        //closing pane
        { "command": "closePane", "keys": "ctrl+shift+w" },

        //duplicate pane
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" },


    ]
}
